### ISSUE TITLE
Note does not stick to location inside a div with overflow as scroll or auto

### ISSUE THREAD

**Issue by blockberd** [fkling/floatnotes#80]
If you try to stick it to something inside a div which has overflow=scroll or overflow=auto (and scrollbars) it does not stick to that location but to the relative on "on top" of it.

You can try with http://developer.ebay.com/devzone/XML/docs/Reference/ebay/index.html

**Comment by fkling** [comment]
Unfortunately this is the expected behavior. The note is located relative to the whole page, not an element within.
