### ISSUE TITLE
Cannot create new notes on Firefox 37

### ISSUE THREAD

**Issue by giovannibgr** [fkling/floatnotes#82]
After the latest update of Firefox (36.0.4 -> 37) most of the functionality of FloatNotes broke down.

* I cannot create new notes
* editing existing ones seems to work at first, but changes are not saved
* even moving the notes around does not work - the notes stick to the mouse and will not let go of it

I've read some comments about "abandonware" et al, but I hope that at least basic functionality will be kept alive for FloatNotes...

**Comment by fkling** [comment]
I'll see what I can do!

**Comment by igrigorov** [comment]
Thank you very much! :)
